package/yast2-storage.changes, package/yast2-storage.spec, src/modules/StorageProposal.rb
- Added logging to the PostProcessor so it's much easier to check in the logs if making snapshots was even considered there
- Added the missing PostProcessor call to that code path in question
=> Fixed bsc#922308: No snapper config for LVM storage proposal

package/yast2-storage.changes, package/yast2-storage.spec, src/include/partitioning/custom_part_lib.rb, test/Makefile.am, test/storage_boot_on_raid1.rb
PowerPC bootloaders are able to read raid1 partition
Fixes bsc#938170
Signed-off-by: Dinar Valeev <dvaleev@suse.com>
=> Allow /boot on RAID1 for PowerPC

package/yast2-storage.changes, src/include/partitioning/ep-main.rb
It fixes https://bugzilla.suse.com/show_bug.cgi?id=940374. The real problem is that, although the installer warns about converting automatically /boot partition to PReP, it does not nothing about that (on expert partitioner).
=> Fix special /boot handling on SLE12

package/yast2-storage.changes, package/yast2-storage.spec, src/include/partitioning/ep-main.rb
The same fix that PR https://github.com/yast/yast-storage/pull/146 but for SLE12 SP1. Manually tested on ppc64le and x86_64.
=> Fix special /boot handling on SLE12 SP1

package/yast2-storage.changes, package/yast2-storage.spec, src/include/partitioning/custom_part_check_generated.rb, src/include/partitioning/ep-main.rb, test/fixtures/dmraid-ext4-boot-root.ycp, test/fixtures/dmraid-ext4-boot.ycp, test/fixtures/gpt-boot-fat.ycp, test/fixtures/gpt-boot-raid0.ycp, test/fixtures/gpt-boot-raid1.ycp, test/fixtures/gpt-btrfs-boot.ycp, test/fixtures/gpt-btrfs.ycp, test/fixtures/gpt-ppc-btrfs.ycp, test/fixtures/gpt-root-raid0.ycp, test/fixtures/gpt-root-raid1.ycp, test/fixtures/msdos-boot-ext4.ycp, test/fixtures/msdos-boot-fat.ycp, test/fixtures/msdos-btrfs-shadowed.ycp, test/fixtures/msdos-ext4-boot-root.ycp, test/fixtures/msdos-ext4-boot.ycp, test/fixtures/msdos-hfs.ycp, test/fixtures/msdos-root-fat.ycp, test/include/partitioning_custom_part_check_generated_include_test.rb
* Reverts 29b5c41, which broke LVM stuff (and who knows what other stuff).
* Find a different solution for bug ([bsc#940374](https://bugzilla.suse.com/show_bug.cgi?id=940374) as @aschnell suggested).
* Fixes the missing PReP/CHRP message. The old message stated that `/boot` partitions would be converted to PReP/CHRP automatically. That's not true.
=> Fix LVM on expert partitioner

src/include/partitioning/custom_part_check_generated.rb, src/modules/Partitions.rb, test/Makefile.am, test/partitions_test.rb
This is a minor refactoring [proposed by @kobliha](https://github.com/yast/yast-storage/pull/154#discussion_r39385283).
=> Move check about PReP boot needed to Partitions module

package/yast2-storage.changes
This line was introduced in https://github.com/yast/yast-storage/pull/146 (reverted).
=> Remove wrong change regarding bsc#940374

src/modules/StorageProposal.rb
See https://github.com/yast/yast-storage/issues/178
The call to GetControlCfg needs to be moved before setting up the root structure:
PropDefaultFs() returns proposal_root_fs, which has at that point the default value btrfs - so the proposal is always based on btrfs.
GetControlCfg calls SetProposalDefault, which in turn calls SetProposalRootFs to initialise the root fs type from /etc/sysconfig/storage. Switching both commands would make sure, that the proposal honors the user settings.
=> Live installer should honor default fs

package/yast2-storage.changes, package/yast2-storage.spec, src/include/partitioning/custom_part_dialogs.rb
As discussed in https://github.com/yast/yast-storage/pull/170 making new request to get rid of the noise commits.
Resolves issue regarding YaST2 partitioning module allowing you to enter an empty subvolume name.
=> Fix boo#955103

package/yast2-storage.changes, package/yast2-storage.spec, src/lib/storage/disk_analyzer.rb, src/lib/storage/disk_size.rb, src/lib/storage/space_maker.rb, src/lib/storage/storage_proposal.rb, test/disk_size_test.rb
This is not complete according to the PBI yet.
(Major) changes to the last version:
- Now using device names wherever possible, not C++ -meets-Ruby-objects from libstorage
(this should be easier to test in an isolated way)
- Use libstorage-bgl to find unpartitioned space
- Actually change things using libstorage-bgl calls:
Right now, the candidate disk is flattened (destroying all partitions and the partition table) for demonstration purposes.
- Introduced an intermediate libstorage-bgl devicegraph "proposal-base" to handle scenarios where the user selects a disk or partitions to be deleted to make room for the Linux installation (available now, too); that would be a copy of the probed devicegraph with those partitions already deleted. The general idea is to revert to this devicegraph …
=> Tech preview: New proposal based on new libstorage-bgl (part 2)

package/yast2-storage.changes, package/yast2-storage.spec, src/include/partitioning/ep-loop-dialogs.rb, src/include/partitioning/ep-lvm-dialogs.rb, src/include/partitioning/ep-raid-dialogs.rb, src/include/partitioning/ep-tmpfs-dialogs.rb
This is a fix for https://bugzilla.suse.com/show_bug.cgi?id=967191
The bug was introduced here https://github.com/yast/yast-storage/pull/189
Manually tested.
=> Expert part: subvolumes also for LVM and raid (bsc#967191)

src/examples/fake_device_demo.rb, src/examples/probe_to_yaml.rb, src/examples/yaml_writer_demo.rb, src/lib/storage/abstract_device_factory.rb, src/lib/storage/fake_device_factory.rb, src/lib/storage/yaml_writer.rb, test/disk_size_test.rb
This is for the most common use case of many of those classes: You create an instance and use it once to let it execute its main functionality.
=> Cosmetic for one-trick ponies: Additional singleton methods

package/yast2-storage.changes, package/yast2-storage.spec, src/modules/StorageProposal.rb
This is a workaround for https://bugzilla.suse.com/show_bug.cgi?id=983003
The proposal tried to create an illegal 4th partition on a DASD on s/390 in certain scenarios (only 3 partitions are allowed on DASDs). We could not track down the exact problem, but this is a workaround:
The storage proposal tries several modes:
- free: Use available free disk space
- resize: Resize available partitions (Windows on PCs)
- reuse: Reuse existing partitions
- remove: Remove single partitions to make space
- desperate: Delete all partitions on the installation disk
In this workaround, we skip "reuse" and to straight to "desperate", but only if we are installing on DASDs (more specific: if any of the candidate disks is a DASD).
I tested this on a QEMU installation where I temporarily replaced the …
=> 	Never try to reuse partitions if any DASD is involved (bsc#983003)

package/yast2-storage.changes, package/yast2-storage.spec, src/modules/Partitions.rb
Tested manually. Seems to work.
=> Don't oversize /boot in aarch64 with UEFI bsc#984874

package/yast2-storage.changes, package/yast2-storage.spec, src/include/partitioning/custom_part_check_generated.rb
For https://trello.com/c/RZnByOJj/423-3-12-sp2-p1-bug-988783-sles12-sp2-beta4-configuring-a-ppc-prep-boot-partition-on-a-gpt-partition-table-fails-with-an-error.
=> - Fixed message suggesting to add PReP partition (bsc#988783)

package/yast2-storage.changes, package/yast2-storage.spec, src/modules/Storage.rb
Don't check for installer restart as it's not needed anymore after moving self-update to the beginning of the installation.
=> Self update cleanup

src/Makefile.am
Add the missing `lib/storage/subvol.rb` file. I'm not bumping the version number because version 3.1.103 has not been submitted yet.
=> Add subvol.rb to Makefile.am

package/yast2-storage.changes, package/yast2-storage.spec, src/clients/partitions_proposal.rb
https://trello.com/c/XDgl2dj7/816-13-casp-new-all-in-one-dialog
https://github.com/yast/yast-yast2/pull/530
~~So far, the code is a placeholder that just mocks the UI, but already uses the `simple_mode` API.~~
=> Implement simple_mode -> label_proposal (FATE#322328)

package/yast2-storage.changes, package/yast2-storage.spec, src/include/partitioning/custom_part_lib.rb, src/include/partitioning/ep-dialogs.rb, src/modules/FileSystems.rb
https://trello.com/c/4IojS1Y5/490-2-12-sp3-fate-320215-allow-full-lvm-encryption-with-msdos-mbr-without-extra-boot
The FATE request was really about not forcing the user to create a separate /boot partition when using encryption: Grub2 learned how to handle booting from encrypted partitions, from encrypted LVM, even from encrypted RAIDs.
The expert partitioner never enforced that, but it wouldn't let you use a "system mount point" (/, /usr/, /var, /opt (???)) when selecting encryption for a partition. This restriction is now lifted.
Along with it, more restrictions are now lifted: It wouldn't allow a Btrfs partition or LVM logical volume to be encrypted (why??), and it wouldn't allow encryption on an LVM physical volume (which doesn't make any sense since this is exactly what the …
=> Expert partitioner less restrictive with encryption

package/yast2-storage.changes, package/yast2-storage.spec, src/include/partitioning/custom_part_dialogs.rb, src/include/partitioning/custom_part_lib.rb, src/include/partitioning/ep-dialogs.rb
https://fate.suse.com/321094
Moved the "Enable Snapshots" combo box out of the "Edit Subvolumes" dialog (where it was really misplaced) and into the "Edit Partition" dialog.
In case of Btrfs, that check box replaces the "Options" button.
Notice that snapshots can only be configured (automatically) for Btrfs as root filesystem during installation.
Screenshots:
"Edit Partition" dialog with Btrfs on /
Notice the check box below the filesystem type ("Btrfs") combo box:
https://w3.suse.de/~shundhammer/snapshots-checkbox/edit-part-snapshots-btrfs.png
Switching the filesystem type combo box to something else than Btrfs brings back the "Options" button below that combo box and removes the "Snapshots" check box:
https://w3.suse.de/~shundhammer/snapshots-checkbox/edit-part-snapshots-ext2.png
And …
=> Move snapshots combo box to edit partition dialog (Fate#321094)

package/yast2-storage.changes, package/yast2-storage.spec, src/include/partitioning/custom_part_check_generated.rb
https://trello.com/c/vYz5fsL9/483-2-12-sp3-fate-320416-warn-if-user-enables-snapshots-on-too-small-root-filesystem
Screenshot: 
https://w3.suse.de/~shundhammer/snapshots-size-warning/snapshots-size-warning.png
=> Warn user in expert partitioner if Btrfs root partition is too small for snapshots (Fate#320416)

package/yast2-storage.changes, package/yast2-storage.spec, src/lib/storage/used_storage_features.rb, src/modules/Storage.rb
https://bugzilla.suse.com/show_bug.cgi?id=1039830
Added new list for optional packages. If the corresponding storage feature is used, but those packages are not available in the repos, only log a warning and continue anyway.
Tested manually with SLE-12-SP3-Server-DVD-x86_64-Build0405-Media1.iso .
=> Don't complain about unavailable NTFS packages if they are not   in the product's repo (bsc#1039830)

.travis.yml, package/yast2-storage.changes, package/yast2-storage.spec, src/modules/StorageProposal.rb
https://trello.com/c/iOESXcm7/624-5-caasp-hack-separate-data-partition
CaaSP needs a separate partition for /var/lib/docker in the storage proposal, and since this would be very tricky to add to the existing proposal mechanism in yast-storage-old, we suggested to repurpose the _home_ partition for that; it can now get another mount point from control.xml. The mechanics and the other parameters in control.xml (size etc.) are still taken from the _home_ partition / volume.
This is the code part that now uses methods to get and set the mount point for the _home_ partition, no longer literal strings all over the code. The name of that partition ("home") is now in a constant so it is clear which is which - it was very confusing in the old code.
=> Enable using home partition as generic separate data partition

package/yast2-storage.changes, package/yast2-storage.spec, src/modules/StorageProposal.rb
https://trello.com/c/zCKSIBHK/633-1-merge-caasp-hack-for-separate-data-partition-to-sle-12-sp3-branch
Partition-based with ext4 root and separate /home
------------------------------------
Partition-based with ext4 root and no separate /home
------------------------------------
Partition-based with btrfs and no separate /home. Notice the home subvolume.
------------------------------------
LVM with btrfs and separate /home. Notice **no** home subvolume.
------------------------------------
LVM with btrfs and no separate /home. Notice the home subvolume.
------------------------------------
LVM with btrfs and separate /home. Notice no home subvolume.
=> Merged SLE-12-SP2-CASP branch to SLE-12-SP3 branch

Rakefile, package/yast2-storage.changes, package/yast2-storage.spec, src/modules/StorageProposal.rb
https://trello.com/c/SQQ1x4Bg/691-5-suse-caasp-10-p2-1051762-docker-on-xfs-by-default
This makes the filesystem type for both home and root in the storage proposal configurable: When home_fs is configurable, root_fs is only a heartbeat away, and it's trivial to add it at the same time.
Test against SLE-12 SP3:
Test against CaaSP 1.0:
2017-08-16 13:55:59 <1> f218(14753) [libstorage] Storage.cc(dumpCommitInfos):4876 ChangeText
Delete partition /dev/vda2 (29.41 GiB) [destructive]
ChangeText Delete partition /dev/vda3 (7.58 GiB) [destructive]
ChangeText Create root volume /dev/vda2 (29.59 GiB) with btrfs
ChangeText Create volume /dev/vda3 (7.40 GiB) for /var/lib/docker with btrfs
ChangeText Create subvolume @/boot/grub2/i386-pc on device /dev/vda2
ChangeText Create subvolume …
=> Make fs type for home and root configurable

.gitignore, .yardopts, package/yast2-storage.changes, package/yast2-storage.spec, src/modules/StorageProposal.rb
https://trello.com/c/sBRQZEzW/670-3-caasp-p1-bnc-1049108-installer-internal-error-in-storageproposalrb
The relevant commit from that PBI is just one of many here, but we should sync yast-storage-old to master anyway to minimize the confusion.
Since it won't be used very much anymore in factory, having all the CASP and 12-SP2 fixes here won't break anything, and it might actually be useful for some things. For any future developement, yast-storage-ng is used anyway.
To get a better overview what this PR is actually doing, switch to the "files" view here.
Basically it's Arvin's commit for the original bug of that PBI and my hack-upon-the-hack commit to make the filesystem types configurable for the home and the root partition.
=> Merged SLE-12-SP2-CASP and SLE-12-SP3 to master

package/yast2-storage.changes, package/yast2-storage.spec
* It fixes bsc#1071724.
Travis is expected to fail (see [this comment](https://github.com/yast/yast-storage/pull/293#issuecomment-348164397)).
=> Escape %{VERSION} in the spec file

README.md
Without the patch the link is broken when I visit https://github.com/yast/yast-storage/.
=> - fixed hyperlink
