yast/yast-storage

package/yast2-storage.changes, package/yast2-storage.spec, src/modules/StorageControllers.rb
Please review the following changes:
* 1645dbb packaging
* 1328181 loading the correct multipath module
=> [Review] Request from 'schubi2' @ 'yast/yast-storage/review_150714_loading_multipath_module'

package/yast2-storage.changes, package/yast2-storage.spec, src/Makefile.am, src/lib/storage/used_storage_features.rb, src/modules/Storage.rb
Install storage related packages only on demand
(bsc#937040, bsc#907331, bsc#915097) 
https://trello.com/c/NQRRvni6/106-8-sles12-sp1-install-storage-related-packages-only-on-demand
=> Install storage related packages only on demand

test/storage_test.rb
@shundhammer This is just a test case from already LGTMed PR #149 
The code is already in SP1 / master
=> Test case for new Storage.SetUserData function

package/yast2-storage.changes, package/yast2-storage.spec, src/modules/FileSystems.rb
This reverts commit 2499e86a752581e0e10407a2a84f90e2919dc700, reversing
changes made to 8f64243533437f8f926732467dcfa1c8ee8a67fe.
=> Revert "Merge pull request #166 from yast/netdev_fix_SLE-12-GA"

package/yast2-storage.changes, package/yast2-storage.spec, src/modules/FileSystems.rb
This change is not wanted anymore as the root of the issue has been fixed in systemd already, see https://bugzilla.novell.com/show_bug.cgi?id=949683#c28
This reverts commit deefce05a32773247b13253d2daf6850800bc838, reversing
changes made to e5979fb5f30ec3d40544c0f21fd8bee84e7912de.
=> Revert "Merge pull request #169 from yast/netdev_fix_master"

src/Makefile.am, src/lib/storage/boot_requirements_checker.rb, src/lib/storage/free_disk_space.rb, src/lib/storage/partition_creator.rb, src/lib/storage/proposal_settings.rb, src/lib/storage/proposal_volume.rb, src/lib/storage/space_maker.rb, src/lib/storage/storage_proposal.rb
(like just discussed on Jangouts with jsrain, ancorgs, imo, snwint)
=> New storage proposal

package/yast2-storage.changes, package/yast2-storage.spec, src/include/partitioning/custom_part_dialogs.rb, src/modules/Storage.rb
Also detected and fixed bsc#954691
=> Expert partitioner only offers snapshots if supported (bsc#944252)

package/yast2-storage.changes, package/yast2-storage.spec, src/include/partitioning/custom_part_lib.rb, src/include/partitioning/ep-dialogs.rb, src/include/partitioning/ep-hd-dialogs.rb, src/modules/Storage.rb
It also includes some code cleanup and documentation that I needed to add to understand the code.
=> Preserve btrfs options for root (bsc#965279)

src/examples/fake-devicegraphs-yaml-format.md
The location (the examples/) directory is wrong right now, but I didn't want to scatter things all over the place when we intend to split the repos in the near future. We'll have to move this file to some doc/ directory when we are doing that.
=> Documentation of fake device tree YaML format

src/examples/fake-devicegraphs-yaml-format.md, src/examples/fake_probing_demo.rb, src/examples/probe_to_yaml.rb, src/examples/yaml_writer_demo.rb, src/lib/storage/abstract_device_factory.rb, src/lib/storage/disk_size.rb, src/lib/storage/enum_mappings.rb, src/lib/storage/fake_device_factory.rb, src/lib/storage/fake_probing.rb, src/lib/storage/yaml_writer.rb
https://trello.com/c/avIbJtoB/303-2-libstorage-write-mockup-hardware-partitioning-tree-to-yaml-files
=> Added YaML writer

package/yast2-storage.changes, package/yast2-storage.spec, src/modules/StorageProposal.rb
=> New radiobutton-based UI for proposal settings

package/yast2-storage.changes, package/yast2-storage.spec, src/modules/FileSystems.rb, src/modules/Partitions.rb, src/modules/Storage.rb, src/modules/StorageProposal.rb, testsuite/data/Makefile.am, testsuite/data/empty-big-ppc64le-nv/Makefile.am, testsuite/data/empty-big-ppc64le-nv/arch.info, testsuite/data/empty-big-ppc64le-nv/disk_sda.info, testsuite/data/empty-ppc64le-nv/Makefile.am, testsuite/data/empty-ppc64le-nv/arch.info, testsuite/data/empty-ppc64le-nv/disk_sda.info, testsuite/tests/empty-big-ppc64le3.out, testsuite/tests/empty-big-ppc64le3.rb, testsuite/tests/empty-big-ppc64le4.out, testsuite/tests/empty-big-ppc64le4.rb, testsuite/tests/empty-ppc64le4.out, testsuite/tests/empty-ppc64le4.rb, testsuite/tests/empty-ppc64le5.out, testsuite/tests/empty-ppc64le5.rb, testsuite/tests/empty-ppc64le6.out, testsuite/tests/empty-ppc64le6.rb, testsuite/tests/helper.rb
Fixes boo#970582
Signed-off-by: Dinar Valeev <dvaleev@suse.com>
=> Add PowerNV support

package/yast2-storage.changes, package/yast2-storage.spec, src/modules/Storage.rb
Goes together with https://github.com/yast/yast-installation/pull/410
=> Don't ask twice about multipath and LUKS bsc#989770

package/yast2-storage.changes, package/yast2-storage.spec, src/modules/Storage.rb
Fix for https://bugzilla.suse.com/show_bug.cgi?id=996007
=> Don't try to format a partition with file system type 'unknown' 

package/yast2-storage.changes, package/yast2-storage.spec, src/lib/storage/subvol.rb, src/modules/Storage.rb, test/Makefile.am, test/subvol_test.rb
https://fate.suse.com/321737
https://trello.com/c/JdvwBp5G/457-5-microos-12-sp2-move-default-subvolumes-to-control-file
=> Make subvolumes configurable in control.xml

src/Makefile.am
Merge SLE-12-SP2 into CASP branch.
=> Add subvol to makefile casp

src/clients/inst_disk_proposal.rb, src/clients/inst_target_part.rb, src/clients/inst_target_selection.rb, src/modules/StorageProposal.rb
- Don't show [Edit Proposal Settings] button if disabled in control.xml
- Added warning popup for expert partitioner if configured in control.xml
=> Don't show [Edit Proposal Settings] button if disabled in control.xml (Fate#321736)

src/include/partitioning/custom_part_lib.rb
See https://github.com/yast/yast-storage/pull/231
Another PR was opened due to a git push -f.
=> Avoid confusion in small partition warning by displaying also rounded input value (bsc#910791)

package/yast2-storage.changes, package/yast2-storage.spec, src/modules/Storage.rb
* Fixes [bsc#1011541](https://bugzilla.suse.com/show_bug.cgi?id=1011541).
* Manually tested.
=> Fix libstorage initialization (bsc#1011541)

package/yast2-storage.changes, package/yast2-storage.spec, src/modules/Storage.rb
Brings #251 into the `master` branch.
=> Merge CASP into master

package/yast2-storage.changes, package/yast2-storage.spec, src/clients/partitions_proposal.rb
=> Implement simple_mode -> label_proposal (FATE#322328) (CASP->master)

doc/config.xml.description
Part of https://trello.com/c/o9LkrKGc/525-3-read-setting-from-control-file
=> Add missing control.xml settings

package/yast2-storage.changes, package/yast2-storage.spec, src/clients/partitions_proposal.rb
=> in simple_mode, block installation unless snapshots are enabled (bsc#1019652)

package/yast2-storage.changes, package/yast2-storage.spec, src/modules/Storage.rb
=> Removed calls to /sbin/insserv

package/yast2-storage.changes, package/yast2-storage.spec, src/include/partitioning/custom_part_lib.rb
https://bugzilla.suse.com/show_bug.cgi?id=1041737
=> Fixed UI syntax error when adding tmpfs (bsc#1041737)

package/yast2-storage.changes, package/yast2-storage.spec, src/modules/FileSystems.rb, src/modules/StorageSnapper.rb, test/filesystems_test.rb, test/fixtures/subvolumes.yml
This PR fixes several issues: [bsc#1044434](https://bugzilla.suse.com/show_bug.cgi?id=1044434), [bsc#1044250](https://bugzilla.suse.com/show_bug.cgi?id=1044250) and [bsc#988700](https://bugzilla.suse.com/show_bug.cgi?id=988700).
=> Fix default subvolume name detection

package/yast2-storage.changes, package/yast2-storage.spec, src/modules/StorageProposal.rb
_This is just merging that commit from the SLE-12-SP3-CASP branch to master_
Original PR: https://github.com/yast/yast-storage/pull/279
=> Enable using home partition as generic separate data partition

src/modules/StorageProposal.rb
- Check for both nil and empty string
- Don't let the settings from control.xml be overridden again
=> Fixes after more testing

package/yast2-storage.changes, package/yast2-storage.spec, src/modules/StorageProposal.rb
Notice that this will not go to master since it will be different for storage-ng.
=> Merged CASP branch to to SP3

.gitignore, .travis.yml, .yardopts
=> Merge SLE-12-SP2

package/yast2-storage.changes, package/yast2-storage.spec
=> Document fillup-templates path change
